version: '3.8'

services:
  beach-bunny-bot:
    image: noahh99/beach-bunny-april-fools:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/data/logs